name: ahqstore_cli
description: An Official port of the original AHQ Store Rust CLI
version: 0.15.0
repository: https://github.com/ahqstore/cli
executables:
  ahqstore:
platforms:
  windows:
  linux:
  macos:
homepage: https://ahqstore.github.io
issue_tracker: https://github.com/ahqstore/cli/issues
documentation: https://ahqstore.github.io/guide/cli/

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  http: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
